-- AlterTable
-- This migration originally attempted to alter emailSentAt, which was incorrect as the column is added in a later migration.
-- The problematic ALTER COLUMN statement has been removed.
